server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/GitHub/Inflearn_SpringCloud/native-file-repo
        git:
          uri: https://github.com/Sangyong-Jeon/spring-cloud-config.git
#          uri: file:///Users/yong/Documents/GitHub/Inflearn_SpringCloud/springcloud-config
#          username:
#          password:
