server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/yong/Documents/GitHub/Inflearn_SpringCloud/springcloud-config