server:
  port: 8888

encrypt:
  key: abcdefghijklmnopqrstuvwxyz0123456789

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/GitHub/Inflearn_SpringCloud/native-file-repo
        git:
          uri: https://github.com/Sangyong-Jeon/spring-cloud-config.git
#          uri: file:///Users/yong/Documents/GitHub/Inflearn_SpringCloud/springcloud-config
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
