server:
  port: 8761

spring:
  application:
    name: discoveryservice
  # Spring Cloud Config를 사용할 일이 있다면 사용
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false